sudo: required
services:
  - docker

before_install:
  - docker build -t leilanigarciia/docker-react -f Dockerfile.dev .
  
  script:
    - docker run -e CI=true leilanigarciia/docker react npm run test